<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[TC x is Failled]]>
    </line>
    <line>
      <![CDATA[TC z is  Running]]>
    </line>
    <line>
      <![CDATA[TC z is Success]]>
    </line>
    <line>
      <![CDATA[TC w is  Running plz try again]]>
    </line>
    <line>
      <![CDATA[TC w is Success]]>
    </line>
    <line>
      <![CDATA[TC y is Skiped]]>
    </line>
    <line>
      <![CDATA[TC a is  Running plz try again]]>
    </line>
    <line>
      <![CDATA[TC a is Success]]>
    </line>
    <line>
      <![CDATA[TC b is Failled]]>
    </line>
    <line>
      <![CDATA[TC d is  Running]]>
    </line>
    <line>
      <![CDATA[TC d is Success]]>
    </line>
    <line>
      <![CDATA[TC c is Skiped]]>
    </line>
  </reporter-output>
  <suite started-at="2023-07-15T23:16:03 IST" name="Suite" finished-at="2023-07-15T23:16:03 IST" duration-ms="77">
    <groups>
    </groups>
    <test started-at="2023-07-15T23:16:03 IST" name="Test" finished-at="2023-07-15T23:16:03 IST" duration-ms="77">
      <class name="listener.myTest2">
        <test-method signature="x()[pri:0, instance:listener.myTest2@742ff096]" started-at="2023-07-15T23:16:03 IST" name="x" finished-at="2023-07-15T23:16:03 IST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listener.myTest2.x(myTest2.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TC x is Failled]]>
            </line>
          </reporter-output>
        </test-method> <!-- x -->
        <test-method signature="z()[pri:0, instance:listener.myTest2@742ff096]" started-at="2023-07-15T23:16:03 IST" name="z" finished-at="2023-07-15T23:16:03 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC z is  Running]]>
            </line>
            <line>
              <![CDATA[TC z is Success]]>
            </line>
          </reporter-output>
        </test-method> <!-- z -->
        <test-method signature="w()[pri:0, instance:listener.myTest2@742ff096]" started-at="2023-07-15T23:16:03 IST" name="w" finished-at="2023-07-15T23:16:03 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC w is  Running plz try again]]>
            </line>
            <line>
              <![CDATA[TC w is Success]]>
            </line>
          </reporter-output>
        </test-method> <!-- w -->
        <test-method signature="y()[pri:0, instance:listener.myTest2@742ff096]" started-at="2023-07-15T23:16:03 IST" name="y" finished-at="2023-07-15T23:16:03 IST" depends-on-methods="listener.myTest2.x" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method listener.myTest2.y() on instance listener.myTest2@742ff096 depends on not successfully finished methods 
[listener.myTest2.x() on instance listener.myTest2@742ff096]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method listener.myTest2.y() on instance listener.myTest2@742ff096 depends on not successfully finished methods 
[listener.myTest2.x() on instance listener.myTest2@742ff096]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC y is Skiped]]>
            </line>
          </reporter-output>
        </test-method> <!-- y -->
      </class> <!-- listener.myTest2 -->
      <class name="listener.myTest">
        <test-method signature="a()[pri:0, instance:listener.myTest@7a35b0f5]" started-at="2023-07-15T23:16:03 IST" name="a" finished-at="2023-07-15T23:16:03 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC a is  Running plz try again]]>
            </line>
            <line>
              <![CDATA[TC a is Success]]>
            </line>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method signature="b()[pri:0, instance:listener.myTest@7a35b0f5]" started-at="2023-07-15T23:16:03 IST" name="b" finished-at="2023-07-15T23:16:03 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listener.myTest.b(myTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TC b is Failled]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method signature="d()[pri:0, instance:listener.myTest@7a35b0f5]" started-at="2023-07-15T23:16:03 IST" name="d" finished-at="2023-07-15T23:16:03 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC d is  Running]]>
            </line>
            <line>
              <![CDATA[TC d is Success]]>
            </line>
          </reporter-output>
        </test-method> <!-- d -->
        <test-method signature="c()[pri:0, instance:listener.myTest@7a35b0f5]" started-at="2023-07-15T23:16:03 IST" name="c" finished-at="2023-07-15T23:16:03 IST" depends-on-methods="listener.myTest.b" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method listener.myTest.c() on instance listener.myTest@7a35b0f5 depends on not successfully finished methods 
[listener.myTest.b() on instance listener.myTest@7a35b0f5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method listener.myTest.c() on instance listener.myTest@7a35b0f5 depends on not successfully finished methods 
[listener.myTest.b() on instance listener.myTest@7a35b0f5]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC c is Skiped]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
      </class> <!-- listener.myTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
